### ISSUE TITLE
"Cannot read property 'includes' of undefined" when I try to lunch the debugger

### ISSUE THREAD

**Issue by nebiros** [Microsoft/vscode-go#1159]
I'm getting that error when I try to lunch the delve debugger, running a `test` configuration, if I set `remotePath` as `""`, I got a different error, anyway, I set it as `${workspaceRoot}`, this is the whole trace:

```
TypeError: Cannot read property 'includes' of undefined
    at GoDebugSession.findPathSeperator (/Users/nebiros/.vscode/extensions/lukehoban.go-0.6.63/out/src/debugAdapter/goDebug.js:291:20)
    at GoDebugSession.launchRequest (/Users/nebiros/.vscode/extensions/lukehoban.go-0.6.63/out/src/debugAdapter/goDebug.js:306:44)
    at GoDebugSession.DebugSession.dispatchRequest (/Users/nebiros/.vscode/extensions/lukehoban.go-0.6.63/node_modules/vscode-debugadapter/lib/debugSession.js:361:22)
    at GoDebugSession.ProtocolServer._handleData (/Users/nebiros/.vscode/extensions/lukehoban.go-0.6.63/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/nebiros/.vscode/extensions/lukehoban.go-0.6.63/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

I'm in Mac, I install delve through `homebrew`, my vscode configuration:

```
// Place your settings in this file to overwrite the default settings
{
    "editor.tabSize": 2,
    "window.zoomLevel": 1,
    "go.testOnSave": true,
    "go.coverOnSave": true,
    "files.trimTrailingWhitespace": true
}
```

My `launch.json`:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "debug studio-api",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "remotePath": "${workspaceRoot}",
      "port": 2345,
      "host": "127.0.0.1",
      "cwd": "${workspaceRoot}",
      "args": [],
      "env": {},
      "showLog": true
    },
    {
      "name": "test studio-api",
      "type": "go",
      "request": "launch",
      "mode": "test",
      "remotePath": "${workspaceRoot}",
      "port": 2345,
      "host": "127.0.0.1",
      "cwd": "${workspaceRoot}",
      "args": [],
      "env": {},
      "showLog": true
    }
  ]
}
```

**Comment by ramya-rao-a** [comment]
@nebiros The program attribute is missing in your debug configuration.

Are you trying to do remote debugging? If not, then keep `remotePath` as empty string.

Also read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson
