### ISSUE TITLE
TypeError: Cannot read property 'currentGoroutine' of null on debug when input

### ISSUE THREAD

**Issue by jnscode** [Microsoft/vscode-go#1223]
Vscode reported an error when I debug the code below and input some characters in the debug console then press enter
code:
var path string
fmt.Scanln(&path)

error message:
TypeError: Cannot read property 'currentGoroutine' of null
    at GoDebugSession.evaluateRequest (C:\Users\xx\.vscode\extensions\lukehoban.go-0.6.65\out\src\debugAdapter\goDebug.js:703:45)
    at GoDebugSession.DebugSession.dispatchRequest (C:\Users\xx\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\debugSession.js:430:22)
    at GoDebugSession.ProtocolServer._handleData (C:\Users\xx\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\xx\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by ramya-rao-a** [comment]
@jnscode I used your code like this:
```
package main

import (
	"fmt"
)

func main() {
	var path string
	fmt.Scanln(&path)
}
```

- Added a breakpoint at the fmt line
- When the breakpoint was hit, I was able to use the debug console and look at the value of path

Can you share your repro steps as to what exactly you did to get the error?

**Comment by jnscode** [comment]
You do not need to set breakpoints
Start the test program in debug mode, and then type some characters in the debug console, and the problem will appear after you press the Enter key

**Comment by ramya-rao-a** [comment]
The debug console can only evaluate expressions when a breakpoint is hit.
That's how delve works

**Comment by jnscode** [comment]
Hi Ramya,
Can you reproduce the issue?
I have cut a picture and I hope it will help you
My VS code is Chinese, I can't find the settings of the switch language. Please forgive me.
![image](https://user-images.githubusercontent.com/25687718/30850078-f4ef1c74-a2d6-11e7-9d28-77915d2eaab0.png)

**Comment by ramya-rao-a** [comment]
Thanks for sharing your code.
It looks like you are trying to interact with your program via the debug console as stdin.

That is unfortunately not supported at the moment.
This is being tracked in #219 

Please follow that thread, we will update it once we have a solution.
