### ISSUE TITLE
error on fmt.Scanf: "TypeError: Cannot read property 'currentGoroutine' of null"

### ISSUE THREAD

**Issue by edwinprojects** [Microsoft/vscode-go#1254]
I've seem same similar posts, same message error but different input.

In my case I am trying to run a silly hello world reading a string by Scanf and I got the error:

```
Type something:
ed
TypeError: Cannot read property 'currentGoroutine' of null
    at GoDebugSession.evaluateRequest (C:\SomePath\.vscode\extensions\lukehoban.go-0.6.65\out\src\debugAdapter\goDebug.js:703:45)
    at GoDebugSession.DebugSession.dispatchRequest (C:\SomePath\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\debugSession.js:430:22)
    at GoDebugSession.ProtocolServer._handleData (C:\SomePath\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\SomePath\.vscode\extensions\lukehoban.go-0.6.65\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

This is my code:

```
// this is a comment
package main

import (
	"fmt"
)

func main() {

	var input string

	fmt.Print("Type something:")
	fmt.Scanf("%s", &input)
	fmt.Println(input)
}
```

If I remove `fmt.Scanf("%s", &input) `it works fine, of course

thanks

**Comment by ramya-rao-a** [comment]
Currently debugging when reading from stdin is not yet supported. 
See #219

I'll try to get to a solution for that in the coming month

**Comment by edwinprojects** [comment]
not even debugging, just running it with Scanf fails

**Comment by ramya-rao-a** [comment]
@edwinprojects You mean by using the `Debug: Start without Debugging` command or `Ctrl+F5` ?
