### ISSUE TITLE
Format on save (goreturns) no longer works after upgrade

### ISSUE THREAD

**Issue by matthewmueller** [Microsoft/vscode-go#1333]
Everytime I try and save, I see this in the console:

```
[Extension Host] TypeError: Cannot add property 0, object is not extensible
	at Array.push (<anonymous>)
	at Promise (/Users/matt/.vscode-insiders/extensions/lukehoban.go-0.6.67/out/src/goFormat.js:23:29)
	at Promise (<anonymous>)
	at Formatter.formatDocument (/Users/matt/.vscode-insiders/extensions/lukehoban.go-0.6.67/out/src/goFormat.js:15:16)
	at document.save.then (/Users/matt/.vscode-insiders/extensions/lukehoban.go-0.6.67/out/src/goFormat.js:70:35)
	at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:65589)
	at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:68936)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:70764)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:70205)
	at e.resolveOk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:352592) (at formatter.formatDocument.then.err (/Users/matt/.vscode-insiders/extensions/lukehoban.go-0.6.67/out/src/goFormat.js:77:29))
```

A bit hard to write go without gofmt and goimports after getting used to them 😅

**Comment by ramya-rao-a** [comment]
Weird, I can repro in Mac but not Windows

**Comment by ramya-rao-a** [comment]
Thanks for the fix @philk 

I have updated a few other places where the array from the configuration was being modified directly. This issue occurs only in the 1.19 Insiders. Folks on VS Code 1.18 should be fine.

I'll release an update next week, until then you can do the below to get the fix beforehand:
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code

**Comment by matthewmueller** [comment]
Thanks for the quick fix!

Yep, I can also confirm that it was only happening on Insiders

**Comment by KISSMonX** [comment]
Thank You.

**Comment by ramya-rao-a** [comment]
The fix is now out in the latest update to the Go extension (0.6.69)
