### ISSUE TITLE
Debug console does not show test failure and associated panic

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-go#1341]
When running tests on the command line:
```
$ go test -v lib/my/package
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test2
--- FAIL: Test2 (0.00s)
        my_test.go:17: oops, something went wrong.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x424fb06]

goroutine 20 [running]:
testing.tRunner.func1(0xc4201241e0)
        /usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x4297920, 0x446a7c0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
lib/my/package.Test2(0xc4201241e0)
        /Users/jpap/PROJECT/.gopath~/src/lib/my/package/my_test.go:19 +0x151
testing.tRunner(0xc4201241e0, 0x42fe350)
        /usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL    lib/my/package  0.017s
$
```

But when running under the debugger, even with full verbosity:
```
Verbose logs are written to:
/var/folders/wc/jkc42h512cv0n1tdp51yjp7w0000gq/T/vscode-go-debug.txt
23:35:52, 2017-11-14
InitializeRequest
InitializeResponse
Using GOPATH: /Users/jpap/PROJECT/.gopath~:/Users/jpap/PROJECT/vendor
Running: /usr/local/bin/dlv test --headless=true --listen=127.0.0.1:2346 --log=true -- -test.v
2017/11/14 23:36:00 server.go:73: Using API v1
2017/11/14 23:36:00 debugger.go:97: launching process with args: [./debug.test -test.v]
API server listening at: 127.0.0.1:2346
InitializeEvent
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
2017/11/14 23:36:00 debugger.go:499: continuing
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test2
Failed to continue.
continue state null
```

It would be nice if we could see the panic, stack trace, the final `FAIL` log item, and error message in the VSC debug console (and without having to use the `showLog` or `trace` launch configuration options).

**Comment by ramya-rao-a** [comment]
@jpap Thanks for reporting

Can you provide a sample code for a test that would fail with a panic?
I can then use that to see what exactly do we get back from delve and how best to surface it.

**Comment by jpap** [comment]
Place this is a test file...
```
func TestPanic(t *testing.T) {
	panic("I survived Timmy O'Toole getting trapped in a well... or did I?")
}
```

When trying it out today, I see the debugger is stopping at `runtime.startpanic()`, whereas before it did not... if you can't reproduce it, please go ahead and close this item.  It may very well be because of a dud-version of Delve that I may have been using for a short while.  Thanks for following up.

With the debugger stopped at `startpanic`, I can see the stack trace and it provides a good way to debug panics further.

**Comment by ramya-rao-a** [comment]
In that case, I'll just close this for now.
Thanks!
