### ISSUE TITLE
go-langserver keeps crashing

### ISSUE THREAD

**Issue by sidmishraw** [Microsoft/vscode-go#1372]
go-langserver keeps crashing when I try to hover over methods to see their definition.

Following is the log for go-langserver from the Output pane:
```
langserver-go: reading on stdin, writing on stdout
panic: unknown type *ast.BadExpr

goroutine 28 [running]:
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.(*exprTypeContext).exprType(0xc420314570, 0x18dce60, 0xc42030a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:505 +0x5aa5
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Underlying(0x18dd520, 0xc4202ebc80, 0x3, 0x0, 0x0, 0xc420314570, 0xc4202dca01, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:681 +0x10f
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doTypeMembers(0x18dd520, 0xc4202ebc80, 0x3, 0x0, 0x0, 0xc420314570, 0xc42030a4dc, 0x4, 0xc42015ff68, 0xc420318420)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:571 +0xd6
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doMembers(0x18dd960, 0xc420316be0, 0x4, 0x0, 0x0, 0xc420314570, 0xc42030a4dc, 0x4, 0xc42015ff68)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:553 +0x1e7
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member.func1(0xc42001f440, 0x18dd960, 0xc420316be0, 0x4, 0x0, 0x0, 0xc420314570, 0xc42030a4dc, 0x4)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:171 +0xa0
created by github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:162 +0x1c5
[Info  - 8:59:29 PM] Connection to server got closed. Server will restart.
langserver-go: reading on stdin, writing on stdout
panic: unknown type *ast.BadExpr

goroutine 28 [running]:
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.(*exprTypeContext).exprType(0xc420135800, 0x18dce60, 0xc420141950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:505 +0x5aa5
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Underlying(0x18dd520, 0xc4202e5f80, 0x3, 0x0, 0x0, 0xc420135800, 0xc4202dc801, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:681 +0x10f
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doTypeMembers(0x18dd520, 0xc4202e5f80, 0x3, 0x0, 0x0, 0xc420135800, 0xc420141e2c, 0x4, 0xc42025df68, 0xc4202f7a10)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:571 +0xd6
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doMembers(0x18dd960, 0xc42030cee0, 0x4, 0x0, 0x0, 0xc420135800, 0xc420141e2c, 0x4, 0xc42025df68)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:553 +0x1e7
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member.func1(0xc42001f560, 0x18dd960, 0xc42030cee0, 0x4, 0x0, 0x0, 0xc420135800, 0xc420141e2c, 0x4)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:171 +0xa0
created by github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:162 +0x1c5
[Info  - 8:59:43 PM] Connection to server got closed. Server will restart.
langserver-go: reading on stdin, writing on stdout
panic: unknown type *ast.BadExpr

goroutine 10 [running]:
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.(*exprTypeContext).exprType(0xc420044db0, 0x18dce60, 0xc42013d620, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:505 +0x5aa5
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Underlying(0x18dd520, 0xc4200dd6e0, 0x3, 0x0, 0x0, 0xc420044db0, 0xc4201a7701, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:681 +0x10f
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doTypeMembers(0x18dd520, 0xc4200dd6e0, 0x3, 0x0, 0x0, 0xc420044db0, 0xc42013dafc, 0x4, 0xc42015ff68, 0xc4201fdd10)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:571 +0xd6
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doMembers(0x18dd960, 0xc42025e680, 0x4, 0x0, 0x0, 0xc420044db0, 0xc42013dafc, 0x4, 0xc42015ff68)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:553 +0x1e7
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member.func1(0xc4201bc840, 0x18dd960, 0xc42025e680, 0x4, 0x0, 0x0, 0xc420044db0, 0xc42013dafc, 0x4)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:171 +0xa0
created by github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:162 +0x1c5
[Info  - 8:59:44 PM] Connection to server got closed. Server will restart.
langserver-go: reading on stdin, writing on stdout
[Error - 8:59:45 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
[Error - 8:59:45 PM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0 
panic: unknown type *ast.BadExpr

goroutine 54 [running]:
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.(*exprTypeContext).exprType(0xc42016bf80, 0x18dce60, 0xc4202f7290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:505 +0x5aa5
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Underlying(0x18dd520, 0xc42022b540, 0x3, 0x0, 0x0, 0xc42016bf80, 0xc42015ee01, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:681 +0x10f
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doTypeMembers(0x18dd520, 0xc42022b540, 0x3, 0x0, 0x0, 0xc42016bf80, 0xc4202f776c, 0x4, 0xc420169f68, 0xc420173c80)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:571 +0xd6
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doMembers(0x18dd960, 0xc4202444a0, 0x4, 0x0, 0x0, 0xc42016bf80, 0xc4202f776c, 0x4, 0xc420169f68)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:553 +0x1e7
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member.func1(0xc42001e9c0, 0x18dd960, 0xc4202444a0, 0x4, 0x0, 0x0, 0xc42016bf80, 0xc4202f776c, 0x4)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:171 +0xa0
created by github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:162 +0x1c5
[Info  - 8:59:51 PM] Connection to server got closed. Server will restart.
langserver-go: reading on stdin, writing on stdout
panic: unknown type *ast.BadExpr

goroutine 66 [running]:
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.(*exprTypeContext).exprType(0xc420198050, 0x18dce60, 0xc4201733d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:505 +0x5aa5
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Underlying(0x18dd520, 0xc420262040, 0x3, 0x0, 0x0, 0xc420198050, 0xc4201d3601, 0x0, 0x0, 0x0, ...)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:681 +0x10f
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doTypeMembers(0x18dd520, 0xc420262040, 0x3, 0x0, 0x0, 0xc420198050, 0xc4201738b2, 0x6, 0xc420243f68, 0xc420197320)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:571 +0xd6
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.doMembers(0x18dd960, 0xc4202626c0, 0x4, 0x0, 0x0, 0xc420198050, 0xc4201738b2, 0x6, 0xc420243f68)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:553 +0x1e7
github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member.func1(0xc42001e9c0, 0x18dd960, 0xc4202626c0, 0x4, 0x0, 0x0, 0xc420198050, 0xc4201738b2, 0x6)
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:171 +0xa0
created by github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types.Type.Member
	/Users/sidmishraw/go/src/github.com/sourcegraph/go-langserver/langserver/internal/godef/go/types/types.go:162 +0x1c5
[Error - 8:59:54 PM] Connection to server got closed. Server will not be restarted.
```

My configuration is as follows:

* Go version = `go version go1.9.2 darwin/amd64`

* User specific settings:
```
"go.formatOnSave": false,
"go.enableCodeLens": {
  "references": true,
  "runtest": true
},
"go.formatTool": "goimports",
"go.docsTool": "gogetdoc",
"go.gotoSymbol.includeImports": true,
"files.autoSave": "afterDelay",
"go.inferGopath": true
"go.gopath": "/Users/sidmishraw/go",
"go.autocompleteUnimportedPackages": true,
"go.useCodeSnippetsOnFunctionSuggest": true,
"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
"go.useLanguageServer": true
```

* go-langserver -version = `v2-dev`

* VScode version = `1.18.1`

* OS = `macOS Sierra v10.12.6`

**Comment by jeyanthimuthuram** [comment]
try using `Go: Install/Update tools` to re-install the packages , after installation try restarting your vscode

**Comment by sidmishraw** [comment]
Tried that and it still crashes when I hover the mouse pointer over a method name a few times(mostly 5-6 times). 

The workaround I'm using to get by this issue is a window reload using the `Reload window` command 😭

**Comment by ramya-rao-a** [comment]
This issue was moved to sourcegraph/go-langserver#213
