### ISSUE TITLE
go.liveErrors not working

### ISSUE THREAD

**Issue by Qadric** [Microsoft/vscode-go#1434]
Every time it triggers, it throws 2 errors on the Developer Tools console:
```
[lukehoban.Go]write EPIPE                     mainThreadExtensionService.ts:43

Error: write EPIPE                            mainThreadExtensionService.ts:44
    at exports._errnoException (util.js:1050:11)
    at Socket._writeGeneric (net.js:724:26)
    at Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:670:40)
    at Socket.Writable.end (_stream_writable.js:475:10)
    at Socket.end (net.js:440:31)
    at processFile (C:\Users\Adrian\.vscode\extensions\lukehoban.go-0.6.70\out\src\goLiveErrors.js:85:13)
```

Windows 10
VS Code 1.19.1

**Comment by ramya-rao-a** [comment]
Looks like you might not have the `gotype-live` tool installed.
Can you run `go get -u github.com/tylerb/gotype-live` in your terminal and try again?

**Comment by Qadric** [comment]
It works now, thanks!

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
