### ISSUE TITLE
go commands no longer working 0.6.75

### ISSUE THREAD

**Issue by shindakun** [Microsoft/vscode-go#1510]
After upgrading to 0.6.75 Go commands no longer work on Windows 10. Removed and reinstalled extension with no change. Developer console showing errors at `getToolsEnvVars`.

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4185 TypeError: Cannot read property 'split' of undefined
	at Object.getToolsEnvVars (C:\Users\laytonse\.vscode\extensions\lukehoban.go-0.6.75\out\src\util.js:323:52)
	at Object.goBuild (C:\Users\laytonse\.vscode\extensions\lukehoban.go-0.6.75\out\src\goBuild.js:56:47)
	at Object.check (C:\Users\laytonse\.vscode\extensions\lukehoban.go-0.6.75\out\src\goCheck.js:67:45)
	at runBuilds (C:\Users\laytonse\.vscode\extensions\lukehoban.go-0.6.75\out\src\goMain.js:291:15)
	at goInstallTools_1.updateGoPathGoRootFromConfig.then (C:\Users\laytonse\.vscode\extensions\lukehoban.go-0.6.75\out\src\goMain.js:117:13)
	at <anonymous>
```
Manually setting `go.toolsGopath` didn't seem to make a difference.

```
Version 1.20.0
Commit c63189deaa8e620f650cc28792b8f5f3363f2c5b
Date 2018-02-07T17:09:39.780Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

![image](https://user-images.githubusercontent.com/319128/36070437-6c759d60-0eaf-11e8-8a1c-dc5875483263.png)

**Comment by jackmott** [comment]
same problem for me, started today sometime. also windwos 10, VS Code 1.20, go version 1.9.3

**Comment by ramya-rao-a** [comment]
Sorry for the trouble
Pushed a fix, try the latest update (0.6.76)

Can either of you run `process.env['PATH']`  and `process.env['Path']`in the console and let me know if it returns null or undefined for either or both?

**Comment by shindakun** [comment]
@ramya-rao-a Looking good now. Checked `process.env['PATH']` and `process.env['Path']` (even `process.env['path']`) and they appear to return the expected paths.

**Comment by jackmott** [comment]
all good here as well, thank you!
