### ISSUE TITLE
go.formatTool isn't running.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#1627]
Steps to Reproduce:

1. write code and save it.
2. no formatting happens, also right clicking the document and choosing format doesn't do anything.

Tried with gofmt, goreturns and goimports.

This is printed in the output pane:

```
(my path)>Finished running tool: /home/oneofone/bin/go build -i -o /tmp/go-code-check -v (my pkg)
(my pkg)


(my path)>Finished running tool: /home/oneofone/bin/go vet ./...

(my path)>Finished running tool: /home/oneofone/code/go/bin/megacheck
```

My relevant vscode-go config (which haven't changed in weeks, and it was working fine last night...):

```
"go.formatTool": "gofmt",
	"go.formatFlags": [ "-s" ],
	"go.useCodeSnippetsOnFunctionSuggest": true,
	"go.autocompleteUnimportedPackages": true,
	"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
	"go.docsTool": "gogetdoc",
	"go.lintTool": "megacheck",
	"go.buildFlags": [ "-v" ],
	"go.testFlags": [ "-v" ],
	"go.liveErrors": {
		"enabled": true,
		"delay": 200
	},

	"go.editorContextMenuCommands": {
		"toggleTestFile": true,
		"addTags": true,
		"removeTags": true,
		"testAtCursor": false,
		"testFile": false,
		"testPackage": true,
		"generateTestForFunction": true,
		"generateTestForFile": false,
		"generateTestForPackage": true,
		"addImport": false,
		"testCoverage": true,
		"playground": false
	},
	"go.addTags": {
		"tags": "json",
		"options": "json=omitempty",
		"promptForTags": false,
		"transform": "camelcase"
	},
	"go.coverageDecorator": "gutter",
	"go.useLanguageServer": true,
```

**Comment by OneOfOne** [comment]
Ok so I restarted vscode few times and this resolved itself, I'm confused because I did that earlier and it didn't work.

**Comment by OneOfOne** [comment]
Alright, problem is back:

```
  ERR Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
    at new <anonymous> (/usr/src/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:430:471)
    at asHover (/home/oneofone/.vscode/extensions/lukehoban.go-0.6.78/node_modules/vscode-languageclient/lib/protocolConverter.js:71:16)
    at <anonymous>
```

**Comment by OneOfOne** [comment]
Can this be caused by having multiple instances of vscode open (on different go projects)?

**Comment by OneOfOne** [comment]
Using the current Go-latest.vsx fixes the problem, closing.
