### ISSUE TITLE
Go To Definition (and ctrl+click) randomly stops working and have to kill go-langserver 

### ISSUE THREAD

**Issue by OneOfOne** [microsoft/vscode-go#1628]
Title, it will randomly stop working (more noticeable if i have multiple vscodes running) and I have to kill go-langserver for it to work again.

Been happening for at least 6-7 versions now.

**Comment by nathanhack** [comment]
I'm having the same issue. Usually happens 1-2 times an hour.  I see no correlation with memory (usage 10-70MB).

**Comment by primalmotion** [comment]
Same here

**Comment by ramya-rao-a** [comment]
cc @slimsag @keegancsmith

**Comment by slimsag** [comment]
Sorry to hear you're running into issues. :/ To help us figure out the issue, could you:

1. Provide steps for us to reproduce the issue on e.g. an open source repository?
2. Provide logs (you can find these in `View` -> `Output` and then select `Tasks` dropdown and click `go-langserver`)?
3. When the issue occurs, find the langserver pid (e.g. with `ps aux | grep go-langserver`) and kill it with `kill -SIGQUIT <pid>`. This will dump a stack trace to the logs which will give us an idea of what the language server was doing when it became unresponsive.

**Comment by OneOfOne** [comment]
@slimsag will do when I get a chance.

**Comment by OneOfOne** [comment]
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///home/oneofone/code/go/src/github.com/OneOfOne/xast") is deprecated. Use rootUri instead.
jsonrpc2 handler: notification "textDocument/didOpen" handling error: Open git:/home/oneofone/code/go/src/github.com/OneOfOne/xast/parser.go?%7B%22path%22%3A%22%2Fhome%2Foneofone%2Fcode%2Fgo%2Fsrc%2Fgithub.com%2FOneOfOne%2Fxast%2Fparser.go%22%2C%22ref%22%3A%22~%22%7D: unable to read out-of-workspace resource from virtual file system
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'g' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/xast/xast.go": character 1 is beyond line 103 boundary
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'g' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/xast/xast.go": character 1 is beyond line 103 boundary
jsonrpc2 handler: notification "textDocument/didChange" handling error: received textDocument/didChange for invalid position {'g' '\x01'} on "file:///home/oneofone/code/go/src/github.com/OneOfOne/xast/xast.go": character 1 is beyond line 103 boundary
[Error - 2:14:40 AM] Request textDocument/formatting failed.
  Message: /home/oneofone/code/go/src/github.com/OneOfOne/xast/xast.go:105:30: expected operand, found ',' (and 1 more errors)
  Code: 0 
SIGABRT: abort
PC=0x47e7ee m=0 sigcode=0

goroutine 10 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc4202f6000, 0x1000, 0xc420001b00, 0xc420094080, 0xc42020d200)
	/usr/src/go1.10/src/syscall/asm_linux_amd64.s:18 +0x5 fp=0xc420617948 sp=0xc420617940 pc=0x47e7c5
syscall.read(0x0, 0xc4202f6000, 0x1000, 0x1000, 0xc420094001, 0x0, 0x0)
	/usr/src/go1.10/src/syscall/zsyscall_linux_amd64.go:749 +0x5f fp=0xc4206179a8 sp=0xc420617948 pc=0x47c3ff
syscall.Read(0x0, 0xc4202f6000, 0x1000, 0x1000, 0x279, 0x0, 0x0)
	/usr/src/go1.10/src/syscall/syscall_unix.go:162 +0x49 fp=0xc4206179f0 sp=0xc4206179a8 pc=0x47a889
internal/poll.(*FD).Read(0xc4200be000, 0xc4202f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go1.10/src/internal/poll/fd_unix.go:153 +0x118 fp=0xc420617a40 sp=0xc4206179f0 pc=0x494698
os.(*File).read(0xc42000e010, 0xc4202f6000, 0x1000, 0x1000, 0x100000000000279, 0x0, 0x8)
	/usr/src/go1.10/src/os/file_unix.go:226 +0x4e fp=0xc420617a88 sp=0xc420617a40 pc=0x49cd9e
os.(*File).Read(0xc42000e010, 0xc4202f6000, 0x1000, 0x1000, 0x443218, 0xc420572360, 0x0)
	/usr/src/go1.10/src/os/file.go:107 +0x6a fp=0xc420617af8 sp=0xc420617a88 pc=0x49a03a
main.stdrwc.Read(0xc4202f6000, 0x1000, 0x1000, 0x0, 0x8, 0x0)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/main.go:135 +0x4b fp=0xc420617b40 sp=0xc420617af8 pc=0x918c0b
main.(*stdrwc).Read(0xe3ae10, 0xc4202f6000, 0x1000, 0x1000, 0x0, 0x1, 0xc420572358)
	<autogenerated>:1 +0x52 fp=0xc420617b80 sp=0xc420617b40 pc=0x919372
bufio.(*Reader).fill(0xc420096a80)
	/usr/src/go1.10/src/bufio/bufio.go:100 +0x11e fp=0xc420617bd0 sp=0xc420617b80 pc=0x57509e
bufio.(*Reader).ReadSlice(0xc420096a80, 0xb0870d, 0xc420096ae0, 0xc42376a0f0, 0x0, 0x0, 0x0)
	/usr/src/go1.10/src/bufio/bufio.go:341 +0x2c fp=0xc420617c08 sp=0xc420617bd0 pc=0x575d7c
bufio.(*Reader).ReadBytes(0xc420096a80, 0xc420617d0d, 0x722537, 0xc4204ae5c8, 0x9afe20, 0xc42037e2a0, 0x0)
	/usr/src/go1.10/src/bufio/bufio.go:419 +0x6b fp=0xc420617ce8 sp=0xc420617c08 pc=0x57623b
bufio.(*Reader).ReadString(0xc420096a80, 0x411d0d, 0xc42037e310, 0x10, 0x10, 0x9e5860)
	/usr/src/go1.10/src/bufio/bufio.go:459 +0x38 fp=0xc420617d40 sp=0xc420617ce8 pc=0x576608
github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2.VSCodeObjectCodec.ReadObject(0xc420096a80, 0x9afe20, 0xc42037e310, 0x16, 0xc425d1e4e0)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2/stream.go:136 +0x3b fp=0xc420617da8 sp=0xc420617d40 pc=0x7e9dbb
github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2.(*VSCodeObjectCodec).ReadObject(0xe3ae10, 0xc420096a80, 0x9afe20, 0xc42037e310, 0xc420096a01, 0xc42037e310)
	<autogenerated>:1 +0x52 fp=0xc420617de0 sp=0xc420617da8 pc=0x7ebd52
github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2.(*bufferedObjectStream).ReadObject(0xc420095f00, 0x9afe20, 0xc42037e310, 0xc420096ae0, 0xc42376a0f0)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2/stream.go:63 +0x51 fp=0xc420617e20 sp=0xc420617de0 pc=0x7e9b01
github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc420096ae0, 0xb0a340, 0xc4200260f8)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2/jsonrpc2.go:494 +0x87 fp=0xc420617fc8 sp=0xc420617e20 pc=0x7e8567
runtime.goexit()
	/usr/src/go1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420617fd0 sp=0xc420617fc8 pc=0x45b671
created by github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2.NewConn
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/vendor/github.com/sourcegraph/jsonrpc2/jsonrpc2.go:328 +0x142

goroutine 1 [chan receive]:
main.run(0x1, 0x8, 0x1, 0x0, 0x0)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/main.go:123 +0x307
main.main()
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/main.go:72 +0xd6

goroutine 18 [chan receive]:
github.com/sourcegraph/go-langserver/langserver/internal/gocode.new_file_reader.func1(0xc4201ea010)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/langserver/internal/gocode/utils.go:229 +0x71
created by github.com/sourcegraph/go-langserver/langserver/internal/gocode.new_file_reader
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/langserver/internal/gocode/utils.go:226 +0x88

goroutine 9 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/src/go1.10/src/runtime/time.go:102 +0x166
main.freeOSMemory()
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/main.go:182 +0x2a
created by main.main
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/main.go:55 +0x164

goroutine 36 [chan receive]:
github.com/sourcegraph/go-langserver/langserver.(*HandlerCommon).InitTracer.func1(0xc420096ae0, 0xc4201c80d0)
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/langserver/tracing.go:37 +0x38
created by github.com/sourcegraph/go-langserver/langserver.(*HandlerCommon).InitTracer
	/home/oneofone/code/go/src/github.com/sourcegraph/go-langserver/langserver/tracing.go:36 +0x262

```

@slimsag

**Comment by OneOfOne** [comment]
bump

**Comment by cacothi** [comment]
same here for javascript. It also stopped refering the require links with the hint to show the parameters for the method

**Comment by ramya-rao-a** [comment]
Closing this issue as we have now moved on to using gopls instead of the go-langserver as the language server for choice for this extension.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
