### ISSUE TITLE
Build failing with ENOENT: no such file or directory, uv_os_get_passwd

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1850]
_From 
https://github.com/Microsoft/vscode-go/issues/1844#issuecomment-413186005 by @nboughton_

Build on save functionality is completely broken for me in 1.26. Every time I save I get the following in the console:

 `mainThreadExtensionService.ts:43 [ms-vscode.Go]ENOENT: no such file or directory, uv_os_get_passwd
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
a @ ipc.net.ts:104
n._socketDataListener @ ipc.net.ts:133
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:44 Error: ENOENT: no such file or directory, uv_os_get_passwd
	at Object.goBuild (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goBuild.js:71:102)
	at Object.check (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goCheck.js:75:45)
	at runBuilds (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goMain.js:334:15)
	at vscode.workspace.onDidSaveTextDocument.document (/home/nick/.vscode/extensions/ms-vscode.go-0.6.87/out/src/goMain.js:347:9)
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at e.$acceptModelSaved (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:728:141)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)`

Attempting to use the command pallet to build the current workspace also fails with the following error:

 `notificationsAlerts.ts:39` Error: Running the contributed command:'go.build.workspace' failed.
	at e._executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:713:87)
	at e.$executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:713:479)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)`

**Comment by ramya-rao-a** [comment]
@nboughton I've pushed a fix to master, can you try the below?

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by johanbrandhorst** [comment]
This fixed the build error for me! Thanks!

**Comment by nanohard** [comment]
Confirmed fix for me as well, same issue.

**Comment by nboughton** [comment]
Build on save and error reporting works with this update. Thanks!

**Comment by pierrre** [comment]
It's working for me, thanks! :+1:

**Comment by ironcladlou** [comment]
vscode 1.26 and breadcrumbs work for me using 6614329.

**Comment by ramya-rao-a** [comment]
The fix for this issue is out in the latest update (0.6.88) to the Go extension.
