### ISSUE TITLE
Error on debug project

### ISSUE THREAD

**Issue by sebglon** [Microsoft/vscode-go#2168]
I have an error on debug process
Steps to Reproduce:

Information:
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

vscode-go 0.7.0

1. I run deug unit test and for one breakpoint and package, i have this error
2.

```
  ERR Assertion failed (item already registered: Unable to produce stack trace: "Internal debugger error: runtime error: slice bounds out of range
runtime.call32 (0x4579da)
	/usr/local/go/src/runtime/asm_amd64.s:522
runtime.gopanic (0x42c0f8)
	/usr/local/go/src/runtime/panic.go:513
runtime.panicslice (0x42b069)
	/usr/local/go/src/runtime/panic.go:54
github.com/derekparker/delve/pkg/proc.newCompositeMemory (0x6a79dc)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/mem.go:105
github.com/derekparker/delve/pkg/proc.(*EvalScope).extractVarInfoFromEntry (0x6c8a78)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:878
github.com/derekparker/delve/pkg/proc.(*EvalScope).Locals (0x6d07f0)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:2056
github.com/derekparker/delve/pkg/proc.(*EvalScope).LocalVariables (0x6c678e)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:654
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace (0x72879e)
	/home/sebglon/go/src/github.com/derekparker/delve/service/debugger/debugger.go:970
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace (0x728103)
	/home/sebglon/go/src/github.com/derekparker/delve/service/debugger/debugger.go:948
github.com/derekparker/delve/service/rpc2.(*RPCServer).Stacktrace (0x8c5a8e)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpc2/server.go:176
runtime.call64 (0x457a5a)
	/usr/local/go/src/runtime/asm_amd64.s:523
reflect.Value.call (0x4b2318)
	/usr/local/go/src/reflect/value.go:447
reflect.Value.Call (0x4b1db3)
	/usr/local/go/src/reflect/value.go:308
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x8ce1ac)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpccommon/server.go:320
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x8cc6cb)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpccommon/server.go:322
runtime.goexit (0x4596f0)
	/usr/local/go/src/runtime/asm_amd64.s:1333
"): Error: Assertion failed (item already registered: Unable to produce stack trace: "Internal debugger error: runtime error: slice bounds out of range
runtime.call32 (0x4579da)
	/usr/local/go/src/runtime/asm_amd64.s:522
runtime.gopanic (0x42c0f8)
	/usr/local/go/src/runtime/panic.go:513
runtime.panicslice (0x42b069)
	/usr/local/go/src/runtime/panic.go:54
github.com/derekparker/delve/pkg/proc.newCompositeMemory (0x6a79dc)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/mem.go:105
github.com/derekparker/delve/pkg/proc.(*EvalScope).extractVarInfoFromEntry (0x6c8a78)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:878
github.com/derekparker/delve/pkg/proc.(*EvalScope).Locals (0x6d07f0)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:2056
github.com/derekparker/delve/pkg/proc.(*EvalScope).LocalVariables (0x6c678e)
	/home/sebglon/go/src/github.com/derekparker/delve/pkg/proc/variables.go:654
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace (0x72879e)
	/home/sebglon/go/src/github.com/derekparker/delve/service/debugger/debugger.go:970
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace (0x728103)
	/home/sebglon/go/src/github.com/derekparker/delve/service/debugger/debugger.go:948
github.com/derekparker/delve/service/rpc2.(*RPCServer).Stacktrace (0x8c5a8e)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpc2/server.go:176
runtime.call64 (0x457a5a)
	/usr/local/go/src/runtime/asm_amd64.s:523
reflect.Value.call (0x4b2318)
	/usr/local/go/src/reflect/value.go:447
reflect.Value.Call (0x4b1db3)
	/usr/local/go/src/reflect/value.go:308
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x8ce1ac)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpccommon/server.go:320
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x8cc6cb)
	/home/sebglon/go/src/github.com/derekparker/delve/service/rpccommon/server.go:322
runtime.goexit (0x4596f0)
	/usr/local/go/src/runtime/asm_amd64.s:1333
")
    at Object.t.ok (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:10:540)
    at e.register (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:351:746)
    at new e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:354:393)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:357:712
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sebglon** [comment]
I have the same on insider version.
I have used a debug configuration.
And i have no error on dlv command

**Comment by ramya-rao-a** [comment]
Can you share the debug configuration you used?

**Comment by ramya-rao-a** [comment]
Can you add `"trace": "verbose"` to your debug configuration?
That will print out the exact call being made dlv. You can then use that command (without the --headless argument) in the terminal to see if that succeeds or not
