### ISSUE TITLE
the formatters stopped working.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#2189]
None of the formatters (gofmt/imports/returns) work anymore on save or even by right clicking -> Format Document.

I can confirm running them from the command line works as intended.

my current vscode settings file: https://github.com/OneOfOne/dotfiles/blob/2a4f274f8c1b3b18712a1bba26c07b8814f0b749/.config/Code/User/settings.json

Go settings: 
```json
	"go.formatTool": "goimports",
	"go.buildOnSave": "off",
	"go.vetOnSave": "off",
	"[go]": {
		"editor.formatOnSave": true
	},

	"go.useCodeSnippetsOnFunctionSuggest": true,
	"go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
	"go.autocompleteUnimportedPackages": true,
	"go.gocodeFlags": ["-builtin", "-ignore-case", "-unimported-packages", "-fallback-to-source"],
	"go.docsTool": "gogetdoc",

	"go.lintTool": "golangci-lint",
	"go.lintFlags": ["--fast", "-D=errcheck"],

	"go.liveErrors": {
		"enabled": true,
		"delay": 500
	},

	"go.editorContextMenuCommands": {
		"toggleTestFile": true,
		"addTags": true,
		"removeTags": true,
		"testAtCursor": false,
		"testFile": false,
		"testPackage": true,
		"generateTestForFunction": true,
		"generateTestForFile": false,
		"generateTestForPackage": true,
		"addImport": false,
		"testCoverage": true,
		"playground": false
	},
	"go.addTags": {
		"tags": "json",
		"options": "json=omitempty",
		"promptForTags": false,
		"transform": "camelcase"
	},

	"go.coverOnSingleTest": true,

	"go.gotoSymbol.includeGoroot": true,

	"go.alternateTools": {
		"go-langserver": "golsp"
	},
	"go.useLanguageServer": false,
	"go.languageServerExperimentalFeatures": {
		"format": true,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true
	}
```

**Comment by ramya-rao-a** [comment]
Do you see any errors in the dev console or the extension host logs when manually formatting?
**Dev Console**: Help -> Toggle Developer Tools -> Console
**Extension Host Logs**: View -> Output -> Log (Extension Host)

**Comment by gir** [comment]
I have similar settings but with the language server enabled:
```
...
  "go.liveErrors": {
    "enabled": true,
    "delay": 500
  },
  "go.alternateTools": {
    "go-langserver": "golsp"
  },
  "go.useLanguageServer": true,
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true
  },
...
```

**Dev Console:**
```
Aborted format on save after 750ms
```
**Extension Host Logs:**
nothing

I notice that formatting on save works for go-langserver immediately. For golsp, when used as an alternative, formatting on save does work after a delay. You have to wait a bit to save after typing, probably letting the language server run. It's generally good to save and have a successful format after half a second, probably dependent on the project size.

When typing, tool output is not shown in the Go Output. However if I save I can see `Finished running tool: /usr/local/bin/go build -i -o /var/folders/hn/zl02t5gn0gj6bsygb0wl2wcm0000gn/T/vscode-gowqZ12g/go-code-check foo`. If I try to save immediately after typing, formatting is aborted, generally saving again after the above message successfully formats the file on save.

Hope that makes sense.

**Comment by ramya-rao-a** [comment]
@gir In you case, the timing issue can be fixed by updating the setting `editor.formatOnSaveTimeout`

@OneOfOne are you using modules?

**Comment by OneOfOne** [comment]
@ramya-rao-a I tried with both modules and without, I didn't have a chance to get a debug log, but moving to using bingo fixed the issue.

My current working config in case anyone runs into it:

Install bingo: https://github.com/saibing/bingo/wiki/Install

```
	"go.alternateTools": {
		"go-langserver": "bingo"
	},
	"go.useLanguageServer": true,
	"go.languageServerFlags": ["-format-style=goimports"],
	"go.languageServerExperimentalFeatures": {
		"format": true,
		"autoComplete": true,
		"rename": true,
		"goToDefinition": true,
		"hover": true,
		"signatureHelp": true,
		"goToTypeDefinition": true,
		"goToImplementation": true,
		"documentSymbols": true,
		"workspaceSymbols": true,
		"findReferences": true
	}
```

**Comment by ramya-rao-a** [comment]
@OneOfOne If you can disable the language server and share any errors as described in 
https://github.com/Microsoft/vscode-go/issues/2189#issuecomment-450544504, that would be very helpful.

Note that when using modules, you may have to change the format tool to `gofmt`. If using `goimports`, then use `Go: Install/Update Tools` -> Select `goimports` -> Ok to update it first. `goreturns` (which is the default format tool) does not support modules

**Comment by OneOfOne** [comment]
Sorry, I thought I had replied earlier about that.

1. This problem happens with and without go modules.
2. There is nothing absolutely printed in the extension host log nor vscode console after I either save (I have format on save on) or right click -> format.
3. I tried setting `"editor.formatOnSaveTimeout": 10000, "editor.codeActionsOnSaveTimeout": 10000`, didn't change anything.

I updated `goimports`, even ran it manually from the terminal and using my save-runner extension with onSave hook, it works as intended that way.

**Comment by OneOfOne** [comment]
Ok, so looking in the console I saw an error in [Prettier Now](https://marketplace.visualstudio.com/items?itemName=remimarsal.prettier-now) every time the project got loaded (which is weird because it doesn't have any files that would trigger that extension), so I removed it and formatting seems to work for now.

**Comment by ramya-rao-a** [comment]
Oh! So looks like the other extension was interfering with the formatting.

@gir, Can you try disabling all other extensions and see if that makes any difference?

**Comment by gir** [comment]
@ramya-rao-a Upping the timeout helped `"editor.formatOnSaveTimeout": 1500`, but it's weird that sometimes save formatting is immediate and sometimes it takes a second.

Also disabling other plugins has no effect.

**Comment by xgfone** [comment]
It's solved??

It's not working for me, either.

```
VSCode: 1.30.2
vscode-go: 0.8.0
```

```json
{
    "go.inferGopath": true,
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.ignoreFolders": [
        "vendor",
    ],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true
    }
}
```

no **Extension Host Logs**.

**Dev Console:**
```log
Extension Host
/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266 Debugger listening on ws://127.0.0.1:21663/4a3c679e-09ce-496c-b353-84a651b597db
For help see https://nodejs.org/en/docs/inspector

/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: ""}
t.log @ /C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303
/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] [vscode-icons] v8.0.0 activated!
/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266 Debugger attached.

/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266 Extension Host
/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266 Debugger listening on ws://127.0.0.1:21663/4a3c679e-09ce-496c-b353-84a651b597db
For help see https://nodejs.org/en/docs/inspector

/C:/Users/xgf/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1504   ERR Header must provide a Content-Length property.: Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (C:\Users\xgf\.vscode\extensions\ms-vscode.go-0.8.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:200:27)
	at Socket.<anonymous> (C:\Users\xgf\.vscode\extensions\ms-vscode.go-0.8.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**go-langserver Log:**
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///d:/gopath/src/github.com/xgfone/ship") is deprecated. Use rootUri instead.
tmpfriend: Removing C:\Users\xgf\AppData\Local\Temp\tmpfriend-9488-543050867
```

**Comment by OneOfOne** [comment]
@xgfone this bug was about the default formatter without using `go-langserver`, and it was caused by me having an extension that messed with it.

The default `go-langserver` is buggy / iffy at best, either set `"go.useLanguageServer": false` or use [`bingo`](https://github.com/saibing/bingo) instead:

```
	"go.alternateTools": {
		"go-langserver": "bingo"
	},
	"go.languageServerFlags": ["-format-style=goimports"],
```

**Comment by xgfone** [comment]
@OneOfOne Yes, you are right. It's working. Thanks!!!
