### ISSUE TITLE
vscode-go formatters no longer working

### ISSUE THREAD

**Issue by dnldd** [Microsoft/vscode-go#2336]
I first had goimports not formatting on save then I switched to goreturns as a workaround. That's no longer working for me currently, I even tried gofmts, no dice. From the logs vscode go is throwing an error:
```
[2019-02-16 05:55:13.964] [exthost] [info] extension host started
[2019-02-16 05:55:14.023] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-02-16 05:55:14.023] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2019-02-16 05:55:14.025] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-02-16 05:55:14.025] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2019-02-16 05:55:14.027] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-02-16 05:55:14.028] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2019-02-16 05:55:14.048] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-02-16 05:55:14.048] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2019-02-16 05:55:14.049] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":true,"activationEvent":"*"}
[2019-02-16 05:55:14.049] [exthost] [info] ExtensionService#loadCommonJSModule /home/dnldd/.vscode/extensions/waderyan.gitblame-2.6.3/out/src/index
[2019-02-16 05:55:14.061] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false,"activationEvent":"onLanguage:go"}
[2019-02-16 05:55:14.061] [exthost] [info] ExtensionService#loadCommonJSModule /home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goMain
[2019-02-16 05:55:14.769] [exthost] [info] eager extensions activated
[2019-02-16 05:55:15.245] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:55:15.252] [exthost] [error] Error: name must not be falsy
	at Function.e.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:390)
	at new e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:328)
	at forEach.decl (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:103:26)
	at Array.forEach (<anonymous>)
	at convertToCodeSymbols (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:83:19)
	at runGoOutline.then.decls (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:20:9)
[2019-02-16 05:55:27.516] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:55:27.516] [exthost] [error] Check the console in dev tools to find errors when formatting.
[2019-02-16 05:55:32.437] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:55:32.438] [exthost] [error] Error: name must not be falsy
	at Function.e.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:390)
	at new e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:328)
	at forEach.decl (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:103:26)
	at Array.forEach (<anonymous>)
	at convertToCodeSymbols (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:83:19)
	at runGoOutline.then.decls (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:20:9)
[2019-02-16 05:55:33.222] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:55:33.222] [exthost] [error] Check the console in dev tools to find errors when formatting.
[2019-02-16 05:56:01.472] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-02-16 05:56:01.472] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/configuration-editing/dist/extension
[2019-02-16 05:56:01.484] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-02-16 05:56:01.484] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/json-language-features/client/dist/jsonMain
[2019-02-16 05:56:01.507] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-02-16 05:56:01.507] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/typescript-language-features/dist/extension
[2019-02-16 05:56:36.151] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:56:36.152] [exthost] [error] Error: name must not be falsy
	at Function.e.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:390)
	at new e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:328)
	at forEach.decl (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:103:26)
	at Array.forEach (<anonymous>)
	at convertToCodeSymbols (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:83:19)
	at runGoOutline.then.decls (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:20:9)
[2019-02-16 05:56:38.533] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:56:38.533] [exthost] [error] Check the console in dev tools to find errors when formatting.
[2019-02-16 05:56:43.750] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:56:43.750] [exthost] [error] Error: name must not be falsy
	at Function.e.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:390)
	at new e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:328)
	at forEach.decl (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:103:26)
	at Array.forEach (<anonymous>)
	at convertToCodeSymbols (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:83:19)
	at runGoOutline.then.decls (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:20:9)
[2019-02-16 05:56:45.045] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:56:45.045] [exthost] [error] Check the console in dev tools to find errors when formatting.
[2019-02-16 05:59:09.070] [exthost] [info] extension host started
[2019-02-16 05:59:09.088] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-02-16 05:59:09.088] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2019-02-16 05:59:09.090] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-02-16 05:59:09.090] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/emmet/dist/extension
[2019-02-16 05:59:09.093] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-02-16 05:59:09.093] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/git/dist/main
[2019-02-16 05:59:09.113] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-02-16 05:59:09.114] [exthost] [info] ExtensionService#loadCommonJSModule /usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2019-02-16 05:59:09.115] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":true,"activationEvent":"*"}
[2019-02-16 05:59:09.115] [exthost] [info] ExtensionService#loadCommonJSModule /home/dnldd/.vscode/extensions/waderyan.gitblame-2.6.3/out/src/index
[2019-02-16 05:59:09.125] [exthost] [info] eager extensions activated
[2019-02-16 05:59:22.389] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.Go {"startup":false,"activationEvent":"onLanguage:go"}
[2019-02-16 05:59:22.389] [exthost] [info] ExtensionService#loadCommonJSModule /home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goMain
[2019-02-16 05:59:35.046] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:59:35.048] [exthost] [error] Error: name must not be falsy
	at Function.e.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:390)
	at new e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:344:328)
	at forEach.decl (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:103:26)
	at Array.forEach (<anonymous>)
	at convertToCodeSymbols (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:83:19)
	at runGoOutline.then.decls (/home/dnldd/.vscode/extensions/ms-vscode.go-0.9.2/out/src/goOutline.js:20:9)
[2019-02-16 05:59:48.497] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-02-16 05:59:48.497] [exthost] [error] Check the console in dev tools to find errors when formatting.

```

I have uninstalled and reinstalled the go tools and the vscode extension itself, the issue persists. Please assist, thanks.

**Comment by ramya-rao-a** [comment]
@dnldd Those logs are related to the outline feature and not formatting. Please clear the logs, and then retry formatting to see if you get any errors for formatting.

Here are some additional details that you can provide which can help
- Are you using modules?
- Is formatting an issue only on save or does manual formatting doesn't work either?
- Have you customized the `editor.formatOnSave` setting? Run `Preferences: Open Settings (JSON) to see your modified settings
- Does this happen even on a simple small hello world sample?

**Comment by dnldd** [comment]
Hmm, goreturns is somehow working now.

- Yes, I'm using modules.
- Formatting was an issue on save and via right-clicking selecting "Format document".
- Yes, I have `editor.formatOnSave` set to true in my `settings.json`.
- I was not able to test this bit out before it started working again.

**Comment by lloiser** [comment]
I'm facing this problem also from time to time using `goimports`

The developer tools shows this:
```
log.ts:167  WARN Aborted format on save after 1000ms
console.ts:134 [Extension Host] Formatting took too long(2718ms). Format On Save feature could be aborted.
```

The `Log (window)` shows:
```
[2019-02-19 15:06:24.129] [renderer1] [warning] Aborted format on save after 1000ms
```

When I execute `time goimports ...` with the arguments that are also provided by vscode-go it takes about `1.59 real   1.22 user   3.54 sys`

Note: manually formatting it using `Format Document` works.

**Comment by ramya-rao-a** [comment]
@lloiser The timeout issue with format on save issue can be fixed with updating the `editor.formatOnSaveTimeout` setting

`goreturns` is not known to be working with modules reliably yet. I would suggest to use `goimports` instead. Remember to update your version of `goimports` to get the latest fixes that enables it to work with modules. Run `Go: Install/Update Tools` -> select `goimports` -> Press Ok
