### ISSUE TITLE
Errors after updating go dependencies

### ISSUE THREAD

**Issue by tclass** [Microsoft/vscode-go#236]
Updated all go dependencies for this plugin today and got these errors below. Nothing ist working right now, reinstalled the pluging, restarted code, no luck yet. 
`[Plugin Host] Uncaught Exception:  Error: write EPIPE(anonymous function) @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90 [Plugin Host] Error: write EPIPE
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at WriteWrap.afterWrite (net.js:760:14)(anonymous function) @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113 write EPIPE: Error: write EPIPE
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at WriteWrap.afterWrite (net.js:760:14)e.onUnexpectedError @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113 Cannot read property 'lines' of null: TypeError: Cannot read property 'lines' of null
    at /Users/tclass/.vscode/extensions/lukehoban.Go-0.6.33/out/src/goExtraInfo.js:13:39e.onUnexpectedError @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:113
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:26(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:98emitOne @ events.js:77emit @ events.js:169window.onerror @ /Applications/Visual Studio Code.app/Contents/Resources/atom.asar/renderer/lib/init.js:74t @ abstractTelemetryService.ts:154
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.logException (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:30848)
    at e.log (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:112:10791)
    at t.handleEvent (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:2881)
    at t.e.publicLog (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:66)
    at t.publicLog (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:5108)
    at t.e.flushErrorBuffer (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:30087)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:67:29947onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:29(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:98emitOne @ events.js:77emit @ events.js:169window.onerror @ /Applications/Visual Studio Code.app/Contents/Resources/atom.asar/renderer/lib/init.js:74t @ abstractTelemetryService.ts:154
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Librar…:67 Uncaught TypeError: Cannot convert object to primitive valueClient.trackException @ /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/applicationinsights/Librar…:67e.logException @ aiAdapter.ts:151e.log @ nodeAppInsightsTelemetryAppender.ts:167t.handleEvent @ mainTelemetryService.ts:90e.publicLog @ abstractTelemetryService.ts:251t.publicLog @ electronTelemetryService.ts:61e.flushErrorBuffer @ abstractTelemetryService.ts:121(anonymous function) @ abstractTelemetryService.ts:114
shell.ts:480 Cannot read property 'lines' of null: TypeError: Cannot read property 'lines' of null
    at /Users/tclass/.vscode/extensions/lukehoban.Go-0.6.33/out/src/goExtraInfo.js:13:39e.onUnexpectedError @ shell.ts:480(anonymous function) @ shell.ts:342e.onUnexpectedError @ errors.ts:72u @ errors.ts:87(anonymous function) @ hover.ts:35p @ winjs.base.raw.js:1470n.undefined.F.enter @ winjs.base.raw.js:1176n.undefined.t.Class.define._run @ winjs.base.raw.js:1343n.undefined.t.Class.define._error @ winjs.base.raw.js:1316f @ ipcRemoteCom.ts:92doNTCallback0 @ node.js:420_tickCallback @ node.js:349
shell.ts:480 Cannot read property 'file' of null: TypeError: Cannot read property 'file' of null
    at /Users/tclass/.vscode/extensions/lukehoban.Go-0.6.33/out/src/goDeclaration.js:75:68e.onUnexpectedError @ shell.ts:480(anonymous function) @ shell.ts:342e.onUnexpectedError @ errors.ts:72u @ errors.ts:87(anonymous function) @ goToDeclaration.ts:28p @ winjs.base.raw.js:1470n.undefined.F.enter @ winjs.base.raw.js:1176n.undefined.t.Class.define._run @ winjs.base.raw.js:1343n.undefined.t.Class.define._error @ winjs.base.raw.js:1316f @ ipcRemoteCom.ts:92doNTCallback0 @ node.js:420_tickCallback @ node.js:349
shell.ts:480 Cannot read property 'lines' of null: TypeError: Cannot read property 'lines' of null
    at /Users/tclass/.vscode/extensions/lukehoban.Go-0.6.33/out/src/goExtraInfo.js:13:39
    at process._tickCallback (node.js:369:9)`

**Comment by tclass** [comment]
wow, sry now it works, downloaded the dependecies again...
