### ISSUE TITLE
Error Highlighting, auto import is not enabled

### ISSUE THREAD

**Issue by hasselv** [microsoft/vscode-go#2452]
Hi,

I am using Visual Studio Code Version: 1.33.1 on OS - Ubuntu 18.04.2 LTS
I had installed alll golang extension by "Go: Install Tools"
However, the **error highlighting** and **auto import** is not enabled.

I checked the console by "Developer:Toggle Developer Tools", it shows :

Failed to load resource: the server responded with a status of 404 ()
ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/go/0.6.67/1509825353971/Microsoft.VisualStudio.Code.Manifest:1 

[uncaught exception]: Error: Cannot get property 'webContents' on missing remote object 35
Error: Cannot get property 'webContents' on missing remote object 35
    at throwRPCError (/snap/code/6/usr/share/code/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/snap/code/6/usr/share/code/resources/electron.asar/browser/rpc-server.js:397:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/snap/code/6/usr/share/code/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

Error: Cannot get property 'webContents' on missing remote object 35
Error: Cannot get property 'webContents' on missing remote object 35
    at throwRPCError (/snap/code/6/usr/share/code/resources/electron.asar/browser/rpc-server.js:145)
    at EventEmitter.<anonymous> (/snap/code/6/usr/share/code/resources/electron.asar/browser/rpc-server.js:397)
    at EventEmitter.emit (/snap/code/6/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/events.js:182)
    at WebContents.<anonymous> (/snap/code/6/usr/share/code/resources/electron.asar/browser/api/web-contents.js:294)
    at WebContents.emit (/snap/code/6/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/events.js:182)
    at metaToException (/snap/code/6/usr/share/code/resources/electron.asar/renderer/api/remote.js:271)
    at Object.exception (/snap/code/6/usr/share/code/resources/electron.asar/renderer/api/remote.js:219)
    at metaToValue (/snap/code/6/usr/share/code/resources/electron.asar/renderer/api/remote.js:223)
    at Object.descriptor.get [as webContents] (/snap/code/6/usr/share/code/resources/electron.asar/renderer/api/remote.js:142)
    at x.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3586)
    at layoutParticipants.forEach.e (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5643)
    at Array.forEach (<anonymous>)
    at e.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5643)
    at p.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3499)
    at e.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5033)
    at p.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:445)
    at Object.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:424)
    at viewItems.forEach.e (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:432)
    at Array.forEach (<anonymous>)
    at p.layoutViews (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:432)
    at p.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:427)
    at g.orthogonalLayout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:439)
    at m.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:446)
    at S.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:453)
    at S.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:458)
    at L.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5036)
    at layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:433)
    at e.doLayout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5048)
    at e.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5048)
    at e.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4566)
    at V.layout (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5079)
    at j.onWindowResize (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5461)
    at _register.c.addDisposableListener.e (/snap/code/6/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5460)

In this case what should I do? Thank you

**Comment by ramya-rao-a** [comment]
@hasselv Those errors are coming from VS Code itself and not this extension, please log an issue in the main [VS Code repo](https://github.com/Microsoft/vscode) for these errors.

Regarding this extension, are any of the other basic features of the extension working as expected for you? Like `Go to definition`, auto-completion, formatting etc? Are you using Go modules?

**Comment by bitfield** [comment]
I'm having this problem too. Basically, _nothing_ works. No auto-imports, no autocomplete, no pop-up documentation, no go to definition. Nada. I assume this is `gopls` related.

Code Version 1.33.1 (1.33.1), 
vscode-go 0.10.0

Steps to reproduce:

1. Create a `main.go` file.
2. Enter this code:

```go
package main

func main() {
	os.Exit(1)
}
```

3. Save

I would expect to see an automatic `import "os"` added, but it is not.

If I add it manually, I would expect to be able to hover over the `os.Exit` and see pop-up information about the function. I do not.

If I delete the `Exit(1)`, place the cursor after `os.` and hit Ctrl-Space, I expect to see an auto-complete menu showing the available functions in `os`. Instead I see only the identifiers in the current file (`func`, `import`, `main`, and so on).

**Comment by hasselv** [comment]
I am not using Go modules.
The auto complete and Go definition is fine for me, but the error highlighting and formatting is not work.

**Comment by stamblerre** [comment]
Have you configured your settings as specified here: https://github.com/golang/go/wiki/gopls?

**Comment by bitfield** [comment]
I had not. I have now!

No change that I can see, despite reloading the window.

Is there any helpful debug output that I can give you?

**Comment by stamblerre** [comment]
@bitfield: do you see that `gopls` is running? If you do `Ctrl`+`Shift`+`P` -> "View: Debug Console" and then click on the "Output" tab, do you see `gopls` in the drop-down list titled "Tasks"?

**Comment by ramya-rao-a** [comment]
@bitfield It looks like what you are seeing is very different from what @hasselv who logged this issue is seeing. Please create a new issue with details that @stamblerre has asked above.

@hasselv Can you share the Go related settings you might have set/changed?

**Comment by DevopsDood** [comment]
Had this issue today randomly. Had to urn off the language server setting:`"go.useLanguageServer": false,` then everything started working normally again. Didn't see any errors in console related to this.

**Comment by bitfield** [comment]
See https://github.com/Microsoft/vscode-go/issues/2476

**Comment by hasselv** [comment]
sorry for late response, here is my go settings I have set.

`{
    "go.inferGopath": true,
    "go.formatTool": "gofmt",
    "go.gocodeAutoBuild": true,
    "go.gotoSymbol.includeImports": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "package"
} `

The error highlighting and auto formating is not enable when I save it.

**Comment by stamblerre** [comment]
@hasselv: Are you still encountering issues with `gopls`? If so, please open a new issue on the [Go issue tracker](https://github.com/golang/go/issues/new).

**Comment by ramya-rao-a** [comment]
Closing this issue as we haven't heard back in a while.
Please try the latest version of the extension and `gopls`.
If the issue still persists, please log an issue as @stamblerre mentioned above
