### ISSUE TITLE
HoverProvider raises an exception any time godef fails to return a match at the cursor

### ISSUE THREAD

**Issue by ironcladlou** [Microsoft/vscode-go#255]
This exception is being thrown by the HoverProvider every time my mouse hovers over the editor and godef doesn't return a match.

```
Cannot read property 'lines' of null: TypeError: Cannot read property 'lines' of null
    at /Users/dan/.vscode/extensions/vscode-go/out/src/goExtraInfo.js:13:39
    at process._tickCallback (node.js:369:9)
```

This results in a lot of error noise in the console.

**Comment by ironcladlou** [comment]
A related exception occurs when hovering with the `⌘` key:

```
Cannot read property 'file' of null: TypeError: Cannot read property 'file' of null
    at /Users/dan/.vscode/extensions/vscode-go/out/src/goDeclaration.js:76:68
    at process._tickCallback (node.js:369:9)
```
