### ISSUE TITLE
[error] [ms-vscode.Go] provider FAILED

### ISSUE THREAD

**Issue by pkochubey** [microsoft/vscode-go#2569]
No idea why this happen, FAQ not helped.

```
[2019-06-07 10:31:29.813] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-06-07 10:31:29.813] [exthost] [error] Error: selectionRange must be contained in fullRange
    at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:345:152)
    at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:345:20)
    at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:333:525)
    at asDocumentSymbol (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:360:22)
    at asDocumentSymbol (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:364:31)
    at Array.map (<anonymous>:null:null)
    at Object.asDocumentSymbols (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:357:23)
    at registerLanguageProvider.client.sendRequest.then (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/client.js:983:62)

[2019-06-07 10:31:33.241] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-06-07 10:31:33.241] [exthost] [error] Error: selectionRange must be contained in fullRange
    at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:345:152)
    at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:345:20)
    at new w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:333:525)
    at asDocumentSymbol (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:360:22)
    at asDocumentSymbol (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:364:31)
    at Array.map (<anonymous>:null:null)
    at Object.asDocumentSymbols (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/protocolConverter.js:357:23)
    at registerLanguageProvider.client.sendRequest.then (/Users/pkochubey/.vscode/extensions/ms-vscode.go-0.10.2/node_modules/vscode-languageclient/lib/client.js:983:62)
```

**Comment by pkochubey** [comment]
Hm, happed after fmt.Sprint("%s", "str"), but need Sprintf. But guys, this is bull sheet. Due to this not big issue all works stopped. 🤦‍♂

**Comment by ramya-rao-a** [comment]
@pkochubey Thanks for reporting. Can you provide us a small code sample where you can see this happening? Then, I can try and look into what is exactly causing this
