### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-go#292]
```
TypeError: Cannot read property 'map' of undefined 
at /lukehoban.Go/out/src/goSuggest.js:53:53 
at ChildProcess.exithandler (child_process.js:206:7) 
at emitTwo (events.js:87:13) 
at ChildProcess.emit (events.js:172:7) 
at maybeClose (internal/child_process.js:817:16) 
at Socket.<anonymous> (internal/child_process.js:319:11) 
at emitOne (events.js:77:13) 
at Socket.emit (events.js:169:7) 
at Pipe._onclose (net.js:469:12) 
```

**Comment by lukehoban** [comment]
@jrieken Curious - is there any way to get any of this information for these telemetry error reports:

1) Version of the extension?
2) The source-mapped file/line/col - assuming that we ship source maps in the extension package?

**Comment by lukehoban** [comment]
Fairly confident this was fixed a month ago with https://github.com/Microsoft/vscode-go/commit/457bcde265d6b89fc8cf782652b09ccbd7d7e6f5.
