### ISSUE TITLE
CI: noisy "Unable to read file" error messages 

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-go#2996]
This is not a bug report, but an issue to track test clean up

From successful travis runs, we see error messages like 
```
Unable to read file (EntryNotFound (FileSystemError)): Error: Unable to read file (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///home/travis/gopath/src/github.com/microsoft/vscode-go/.vscode-test/vscode-1.41.1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

Example: https://travis-ci.org/microsoft/vscode-go/jobs/640082000?utm_medium=notification&utm_source=github_status

While probably not affecting the test results, this is distracting and makes it difficult to trust the test results.

**Comment by hyangah** [comment]
@stamblerre This no longer happens - I believe this was fixed in the recent vscode release. Can you close this?
