### ISSUE TITLE
Crash when using gopls and liveshare: only file URIs are supported, got "vsls" from "vsls:/"

### ISSUE THREAD

**Issue by didrocks** [microsoft/vscode-go#3081]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.13.4
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux amd64

### Share the Go related settings you have added/edited

```"go.useLanguageServer": true,
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
    },
    // Optional: Disable snippets, as they conflict with completion ranking.
    "editor.snippetSuggestions": "none",
},
"gopls": {
     // Add parameter placeholders when completing a function.
    "usePlaceholders": true,

    // If true, enable additional analyses with staticcheck.
    // Warning: This will significantly increase memory usage.
    "staticcheck": false,
}
```
### Describe the bug
gopls (version v0.3.3) crashes on startup when connecting to remote liveshare

Here is the logs:
```
Go info
-------
go version go1.13.4 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/didrocks/.cache/go-build"
GOENV="/home/didrocks/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/didrocks/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build341301844=/tmp/go-build -gno-record-gcc-switches"

panic: only file URIs are supported, got "vsls" from "vsls:/"

goroutine 48 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/span/uri.go:32
golang.org/x/tools/internal/lsp/cache.(*view).getGoEnv(0xc000212f00, 0xe50f80, 0xc000311f50, 0xc00032e000, 0x68, 0x68, 0xc0003bc701, 0x0, 0xc000450e58, 0x40ddb4)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/cache/view.go:693 +0x7ef
golang.org/x/tools/internal/lsp/cache.(*view).setBuildInformation(0xc000212f00, 0xe50f80, 0xc000311f50, 0xc00036e4f0, 0x6, 0xc00032e000, 0x68, 0x68, 0x1, 0x0, ...)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/cache/view.go:580 +0x8f
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0002d0840, 0xe50f80, 0xc000311f50, 0xc00036e4f8, 0x4, 0xc00036e4f0, 0x6, 0x4000000000000000, 0x10101, 0xc00036e448, ...)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/cache/session.go:138 +0x4e6
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0002d0840, 0xe50f80, 0xc000311f50, 0xc00036e4f8, 0x4, 0xc00036e4f0, 0x6, 0x4000000000000000, 0x10101, 0xc00036e448, ...)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/cache/session.go:90 +0x13d
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0001dda00, 0xe50f80, 0xc000311f50, 0xc00036e4f8, 0x4, 0xc00036e4f0, 0x6, 0xac2c0c, 0xe50f80, 0xc000311f50, ...)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/workspace.go:42 +0x1fe
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0001dda00, 0xe50f80, 0xc000311f50, 0xc0002b0200, 0x1, 0x4)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/general.go:169 +0x184
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0001dda00, 0xe50f80, 0xc000311f50, 0x13988d8, 0x0, 0x0)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/general.go:157 +0x263
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc0001dda00, 0xe50f80, 0xc000311f50, 0x13988d8, 0x13988d8, 0x0)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/server_gen.go:112 +0x49
golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0xe6f200, 0xc0001dda00, 0xe50f80, 0xc000311f50, 0xc00030d340, 0x0, 0x0)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/lsp/protocol/tsserver.go:110 +0x970
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc0001cc6c0, 0xc00030d340, 0xc000309b60, 0xe50f80, 0xc000311f50, 0x0, 0x0, 0xc000193be0)
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/jsonrpc2/jsonrpc2.go:372 +0x170
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/home/didrocks/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200227200655-6862ededa516/internal/jsonrpc2/jsonrpc2.go:356 +0x84d
[Info  - 17:40:33] Connection to server got closed. Server will restart.
[Info  - 17:40:33] 2020/03/03 17:40:33 Build info
----------
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200227200655-6862ededa516 h1:OX66ZzpltgCOuBSGdaeT77hS2z3ub2AB+EuGxvGRBLE=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

**Comment by stamblerre** [comment]
Thanks for the report! @heschik has looked into supporting non-file URIs, I believe. In general, we should probably investigate support for `gopls` in live share.

**Comment by heschik** [comment]
In general this doesn't look very feasible to me; even if we process almost everything as an overlay, we still need a filesystem location for the `go.mod` and to root the overlay. `vsls:/` gives us nothing.

Is there any documentation on how VSLS works? I couldn't find any offhand. Do we actually need to have gopls run locally, or only on the session host?

**Comment by didrocks** [comment]
Yeah, I was thinking at first that it was the other host gopls which was sending linting and other hints to all guests.

However, until gopls v0.3.2, the local version was running for everyone, and we were regularly asynced/stucked between the liveshare host and the guests (gopls didn’t really work well with liveshare after more than a couple of hours, didn’t find anything reproducible but could be due to liveshare having issues syncing files edited outside of the editor, like generated golden test files). However, at least some linting (until some point it started to be stuck and we had to restart the session) was available. Currently, with v0.3.3, there is none anymore for the guests.

I agree that (from a thousand feet perspective) everything should be transmitted to the multiple guests via LSP protocol on liveshare from the host gopls.

**Comment by stamblerre** [comment]
I believe that LSP may have some support for remote files (see https://github.com/golang/go/issues/31086). We'll try to investigate this and see how we can make it work better, but it probably won't be prioritized till after `gopls/v1.0.0`.

**Comment by bitfield** [comment]
Same problem here. This is making `gopls` almost unusable over Live Share, because the language server crashes repeatedly and is then disabled, and I think this is causing an ever-spinning 'Getting code actions...' dialog, which causes the sharing to stop. So every time I make an edit, VS Code tries to auto-save, and because I have format on save enabled, it's trying to call `gopls`, which is not there, so the share session gets jammed. The only way around this seems to be continually clicking 'Cancel' on the 'Getting code actions' dialog, which is annoying.

It seems like it doesn't make sense for _my_ `gopls` to be doing anything on the remote file, doesn't it? Could we just disable it altogether in a Live Share session?

```
panic: only file URIs are supported, got "vsls" from "vsls:/"

goroutine 75 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/span/uri.go:32
golang.org/x/tools/internal/lsp/cache.(*view).getGoEnv(0xc0003be000, 0x1a12580, 0xc000251ec0, 0xc000262000, 0x2b, 0x2b, 0x203000, 0x203000, 0x203000, 0x20abc88)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/cache/view.go:693 +0x87c
golang.org/x/tools/internal/lsp/cache.(*view).setBuildInformation(0xc0003be000, 0x1a12580, 0xc000251ec0, 0xc000311900, 0x6, 0xc000262000, 0x2b, 0x2b, 0x5f5e101, 0x0, ...)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/cache/view.go:580 +0x8f
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0002482c0, 0x1a12580, 0xc000251ec0, 0xc000311910, 0xf, 0xc000311900, 0x6, 0x4000000000000000, 0x10101, 0xc000311860, ...)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/cache/session.go:138 +0x4e6
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0002482c0, 0x1a12580, 0xc000251ec0, 0xc000311910, 0xf, 0xc000311900, 0x6, 0x4000000000000000, 0x10101, 0xc000311860, ...)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/cache/session.go:90 +0x12c
golang.org/x/tools/internal/lsp.(*Server).addView(0xc00021ef80, 0x1a12580, 0xc000251ec0, 0xc000311910, 0xf, 0xc000311900, 0x6, 0x1f67018, 0x0, 0x0, ...)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/workspace.go:42 +0x1fe
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc00021ef80, 0x1a12580, 0xc000251ec0, 0xc0000e9f00, 0x1, 0x4)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/general.go:169 +0x184
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc00021ef80, 0x1a12580, 0xc000251ec0, 0x1f67018, 0x0, 0x0)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/general.go:157 +0x262
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc00021ef80, 0x1a12580, 0xc000251ec0, 0x1f67018, 0x1f67018, 0x0)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/server_gen.go:112 +0x49
golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0x1a2cd80, 0xc00021ef80, 0x1a12580, 0xc000251ec0, 0xc00024b880, 0x0, 0x0)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/protocol/tsserver.go:110 +0x936
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc00020eae0, 0xc00024b880, 0xc000252b40, 0x1a12580, 0xc000251ec0, 0x0, 0x0, 0xc000201d60)
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/jsonrpc2/jsonrpc2.go:372 +0x160
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/Users/john/go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/jsonrpc2/jsonrpc2.go:356 +0x850
[Info  - 5:31:24 PM] Connection to server got closed. Server will restart.
[Error - 5:31:24 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 5:31:24 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 5:31:24 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/john/.vscode/extensions/ms-vscode.go-0.13.1/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Info  - 5:31:24 PM] 2020/04/02 17:31:24 Build info
----------
golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a h1:hKrQy/q8/Xivoqgw6nGiz1jqpn1WGBLDcWLZwW0983E=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.14 darwin/amd64

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/john/Library/Caches/go-build"
GOENV="/Users/john/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/john/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q3/ybqqxyh92yd0yc865zqk0vpm0000gn/T/go-build879540024=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by stamblerre** [comment]
@bitfield: I would recommend setting `"go.useLanguageServer": false` when using live share, for now.

We can probably disable `gopls` when we see a `vsls://` file URI, or `gopls` can check the root URI and return an error. I'll mail a change for `gopls`.

**Comment by bitfield** [comment]
Woohoo! You're crushing it, @stamblerre! Thanks a lot.

**Comment by didrocks** [comment]
Thanks a lot @stamblerre :)

**Comment by stamblerre** [comment]
Closing this issue as the crash has been resolved in `gopls`. Support for `gopls` in VSLS is currently not prioritized, but the most relevant issue to follow along with is https://github.com/golang/go/issues/31086.
