### ISSUE TITLE
gopls does not start behind a blocking proxy

### ISSUE THREAD

**Issue by neclepsio** [microsoft/vscode-go#3204]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.14.2
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.44.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.11.4
- Run `go env GOOS GOARCH` to get the operating system and processor architecture details
	- windows amd64

### Describe the bug
Behind a proxy which redirects to a login page, `golps` does not start. Apprently, it fails checking the version. The following error is printed in developer tools console. When VS Code is started with internet connection, the server works correctly.

```
console.ts:137 [Extension Host] stack trace: TypeError: Invalid Version: null
	at new SemVer (c:\[...]\Microsoft VS Code\code-portable-data\extensions\ms-vscode.go-0.14.1\node_modules\semver\semver.js:314:11)
	at compare (c:\[...]\Microsoft VS Code\code-portable-data\extensions\ms-vscode.go-0.14.1\node_modules\semver\semver.js:647:10)
	at rcompare (c:\[...]\Microsoft VS Code\code-portable-data\extensions\ms-vscode.go-0.14.1\node_modules\semver\semver.js:664:10)
	at Array.sort (<anonymous>)
	at c:\[...]\Microsoft VS Code\code-portable-data\extensions\ms-vscode.go-0.14.1\out\src\goLanguageServer.js:428:18
	at Generator.next (<anonymous>)
	at fulfilled (c:\[...]\Microsoft VS Code\code-portable-data\extensions\ms-vscode.go-0.14.1\out\src\goLanguageServer.js:9:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by neclepsio** [comment]
Upon further inspection, at `goLanguageServer.js:428`, `versions` is `[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]`.

**Comment by ramya-rao-a** [comment]
The latest update 0.14.2 has the fix for this, Thanks @neclepsio
