### ISSUE TITLE
Activating extension `lukehoban.Go` failed: Cannot find module '/Users/jonathan/vscode-go/out/src/goMain'.

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode-go#35]
Following the building and debugging instructions, when I open go source files in the Exntesion Development Host I get this:

```
Activating extension `lukehoban.Go` failed:  Cannot find module '/Users/jonathan/vscode-go/out/src/goMain'
Here is the error stack:  Error: Cannot find module '/Users/jonathan/vscode-go/out/src/goMain'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:18:17333)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:1298)
    at u (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:12:20550)
    at t._loadPluginModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:12:24382)
    at t.e._actualActivatePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:11:29061)
    at t._actualActivatePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:12:24874)

```

**Comment by lukehoban** [comment]
That would happen if you haven't compiled the `.ts` files to `.js` (they are placed in the `/out/` subfolder). But the compilation should happen automatically when you hit `F5`.  You could try invoking `Tasks: Run Build Task` manually, but that shouldn't be needed.

Did you run the `npm install` in the steps in the readme?

**Comment by jchannon** [comment]
Fixed in #33

**Comment by jchannon** [comment]
Run Build Task produces
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compile' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info precompile Go@0.6.7
6 info compile Go@0.6.7
7 verbose unsafe-perm in lifecycle true
8 info Go@0.6.7 Failed to exec compile script
9 verbose stack Error: Go@0.6.7 compile: `node ./node_modules/vscode/bin/compile -watch -p ./`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid Go@0.6.7
11 verbose cwd /Users/jonathan/vscode-go
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error Go@0.6.7 compile: `node ./node_modules/vscode/bin/compile -watch -p ./`
17 error Exit status 1
18 error Failed at the Go@0.6.7 compile script 'node ./node_modules/vscode/bin/compile -watch -p ./'.
18 error This is most likely a problem with the Go package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./node_modules/vscode/bin/compile -watch -p ./
18 error You can get their info via:
18 error     npm owner ls Go
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by lukehoban** [comment]
The changes in #33 should not be needed, as there is a devDependency on `vscode` which includes a copy of the TypeScript compiler, and is invoked by the `compile` target in `package.json`, which is itself invoked by the `npm` target in `tasks.json`, which is invoked by the `preLaunchTask` in `launch.json`.

All of that is standard setup for VS Code extensions, so I'd be a bit surprised if it wasn't working.

Are you sure you ran npm install?  Do you have a `vscode` folder in your `node_modules`?

**Comment by lukehoban** [comment]
Yes - your more recent post also suggests that you don't have node modules installed correctly - specifically `./node_modules/vscode/bin/compile`.

**Comment by jchannon** [comment]
Yup ran npm install  as per the instructions. Do you require a specific version of node/npm? You can see my versions in the log above

**Comment by lukehoban** [comment]
Could be a Node version problem.  I'm not certain what the min requirement is.  I'm on 4.1.1.

What do you see if you manually run `node ./node_modules/vscode/bin/compile -watch -p ./`?

**Comment by jchannon** [comment]
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/Users/jonathan/vscode-go/node_modules/vscode/bin/compile:4:40)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by lukehoban** [comment]
What do you see from `tree node_modules/vscode/node_modules/typescript`:

```
lukeh@Lukes-MacBook-Pro:~/dd/vscode-go$ tree node_modules/vscode/node_modules/typescript/
node_modules/vscode/node_modules/typescript/
├── AUTHORS.md
├── CONTRIBUTING.md
├── CopyrightNotice.txt
├── Jakefile.js
├── LICENSE.txt
├── README.md
├── ThirdPartyNoticeText.txt
├── bin
│   ├── tsc
│   └── tsserver
├── lib
│   ├── lib.core.d.ts
│   ├── lib.core.es6.d.ts
│   ├── lib.d.ts
│   ├── lib.dom.d.ts
│   ├── lib.es6.d.ts
│   ├── lib.scriptHost.d.ts
│   ├── lib.webworker.d.ts
│   ├── tsc.js
│   ├── tsserver.js
│   ├── typescript.d.ts
│   ├── typescript.js
│   ├── typescriptServices.d.ts
│   └── typescriptServices.js
├── package.json
└── tslint.json

2 directories, 24 files
```

Assuming that those are installed, my only next guess would be to try upgrading Node and see if that works.

**Comment by jchannon** [comment]
That directory doesn't exist :(

**Comment by jchannon** [comment]
```
npm install                                                           
json-rpc2@1.0.2 node_modules/json-rpc2
├── object-assign@4.0.1
├── eventemitter3@1.1.1
├── jsonparse@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── lodash@3.10.1
├── faye-websocket@0.10.0 (websocket-driver@0.6.3)
└── es5class@2.3.1 (better-curry@1.6.0)

vscode@0.10.4 node_modules/vscode
├── source-map-support@0.3.3 (source-map@0.1.32)
├── mocha@2.3.4 (escape-string-regexp@1.0.2, supports-color@1.2.0, growl@1.8.1, commander@2.3.0, diff@1.4.0, debug@2.2.0, jade@0.26.3, mkdirp@0.5.0, glob@3.2.3)
└── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@3.0.0)

fs-extra@0.26.2 node_modules/fs-extra
├── path-is-absolute@1.0.0
├── klaw@1.1.2
├── jsonfile@2.2.3
├── graceful-fs@4.1.2
└── rimraf@2.4.3 (glob@5.0.15)
```

**Comment by jchannon** [comment]
Looks like `typescript` is a missing dependency?

**Comment by egamma** [comment]
yes add typescript as a devDependency
		"typescript": "^1.6.2",

**Comment by egamma** [comment]
We have changed the dependency of the vscode module. it no longer has typescript as a devdependency.

**Comment by lukehoban** [comment]
Ahh - great - thanks @egamma.  I'll add the devDependency to the extension package directly then.

**Comment by jchannon** [comment]
can confirm this fixes it
