### ISSUE TITLE
Debugging Debugger

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode-go#554]
Steps to debug the debugger don't seem to be working on "master" branch - I am getting:

```
Debugger listening on port 19032
module.js:327
    throw err;
    ^

Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\gordon\git\vscode-ecl\out\src\eclClientTools.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
Reverting to ~~v0.63~~ v0.6.43 resolves the issue.

I think its due to the version change of the vscode engine, but am very new to the whole vscode eco-system.

**Comment by ramya-rao-a** [comment]
@GordonSmith How about reverting to 0.6.45? Does that work for you?

@roblourens Your latest commit to `goDebug.ts` adds a dependency to `utils.ts` which in turn needs the `vscode` module. May be thats the root cause?

**Comment by GordonSmith** [comment]
There is no 0.6.45 (I had a typo in my comment above - now fixed).

**Comment by roblourens** [comment]
I just merged that PR, it wasn't in master 7 hours ago

**Comment by roblourens** [comment]
@GordonSmith Did you run npm install? Does that module exist?

**Comment by GordonSmith** [comment]
Yup did the whole npm install/clean re-install thing, like I say it works on the older fork, but not on master.

**Comment by GordonSmith** [comment]
Hmm working on current master - going to close as invalid while a diff my changes again - thx for looking into it.
