### ISSUE TITLE
Seems to fail on latest insiders build

### ISSUE THREAD

**Issue by dchw** [Microsoft/vscode-go#836]
- VSCode Version: 1.11.0-insider (Commit 84e56fc5)
- OS Version: Windows 10

The golang plugin seems to have troubles loading on the latest release. The console has the following stack trace:

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'packageJSON' of undefined
    at Object.<anonymous> (C:\Users\corey.larson\.vscode-insiders\extensions\lukehoban.go-0.6.54\out\src\util.js:12:69)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:14:9924)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\corey.larson\.vscode-insiders\extensions\lukehoban.go-0.6.54\out\src\goSuggest.js:9:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.o._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:14:9924)
```

Steps to Reproduce:

1. Install vscode-go
2. Restart VSCode to load extension
3. Try to edit go code and see that it doesn't seem to work

**Comment by ramya-rao-a** [comment]
@sandy081 FYI recent changes to https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensions/common/abstractExtensionService.ts causes the `vscode.extensions.getExtension` to return `undefined`

The Go extension fails to activate due to https://github.com/Microsoft/vscode-go/blob/54b720d3ef30b2e70c442609b2477b3e1dba2985/src/util.ts#L13

The changes have been reverted in master, so the next insiders should be ok.

**Comment by sandy081** [comment]
@ramya-rao-a Made some changes last week to make extension ids case insensitive and reverted them on last Friday. Refer to the [issue](https://github.com/Microsoft/vscode/issues/19685) for more information. So this would be good with latest insiders.

**Comment by ramya-rao-a** [comment]
Thanks @sandy081
