### ISSUE TITLE
Debugging crashes when I use a dependency with CGO

### ISSUE THREAD

**Issue by murz** [Microsoft/vscode-go#85]
Hi,

First, thanks so much for this awesome project! VSCode is now a really great way to program go!

I'm trying to get dubugging to work in my project. I was able to get it working in a simple project, but in my "real" project it crashes whenever I try to run from the debugger. From the stack trace, it seems like it's tripping up on this library I use: http://github.com/ry/v8worker  which in turn uses some C code.

Here is what I see in the debug console when it crashes:
```
2015/11/24 12:40:06 debugger.go:56: launching process with args: [./debug]
2015/11/24 12:40:08 server.go:301: method Run has wrong number of ins: 1
2015/11/24 12:40:08 server.go:301: method Stop has wrong number of ins: 2
2015/11/24 12:40:08 debugger.go:231: continuing
2015/11/24 12:40:08 debugger.go:174: created breakpoint: &api.Breakpoint{ID:1, Addr:0x44ab1f8, File:"/Users/mike/Code/nourish/server/src/nourish-server/server.go", Line:61, FunctionName:"main.main", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2015/11/24 12:40:08 debugger.go:174: created breakpoint: &api.Breakpoint{ID:2, Addr:0x44ab805, File:"/Users/mike/Code/nourish/server/src/nourish-server/server.go", Line:106, FunctionName:"main.main", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2015/11/24 12:40:08 debugger.go:174: created breakpoint: &api.Breakpoint{ID:3, Addr:0x4521a74, File:"/Users/mike/Code/nourish/server/src/nourish-server/auth/auth.go", Line:40, FunctionName:"nourish-server/auth.Mount.func2", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
time="2015-11-24T12:40:08-08:00" level=info msg="ReactJS rendering engine: v8" 
2015/11/24 12:40:16 debugger.go:231: continuing

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x42e9e61]
runtime stack:
runtime.throw(0x4cdae00, 0x2a)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40028a0, 0xc8201d1658, 0xc800000000)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc8201d1628 sp=0xc8201d15f8
github.com/ry/v8worker._Cfunc_worker_new(0x4002d70, 0xc820238f90, 0x0)
	github.com/ry/v8worker/_obj/_cgo_gotypes.go:120 +0x36 fp=0xc8201d1658 sp=0xc8201d1628
github.com/ry/v8worker.New(0xc820238f80, 0xc820238f80)
	/Users/mike/Code/go/src/github.com/ry/v8worker/worker.go:51 +0x87 fp=0xc8201d1688 sp=0xc8201d1658
nourish-server/apps/react.newV8Worker(0xc82024c510, 0x0)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/react/v8.go:249 +0x140 fp=0xc8201d18d8 sp=0xc8201d1688
nourish-server/apps/react.newV8Pool(0xc82024c510, 0x0)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/react/v8.go:134 +0xde fp=0xc8201d1928 sp=0xc8201d18d8
nourish-server/apps/react.V8ReactEngine.LoadApp(0xc82024c510, 0x0, 0x0)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/react/v8.go:24 +0x31 fp=0xc8201d1980 sp=0xc8201d1928
nourish-server/apps/react.(*V8ReactEngine).LoadApp(0x51fdab0, 0xc82024c510, 0x0, 0x0)
	<autogenerated>:2 +0xa6 fp=0xc8201d19c8 sp=0xc8201d1980
nourish-server/apps/react.LoadApp(0xc82024c510, 0x0, 0x0)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/react/react.go:35 +0x47 fp=0xc8201d1a00 sp=0xc8201d19c8
nourish-server/apps.loadHQApp(0xc820234690, 0x0, 0x0)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/hq.go:70 +0x824 fp=0xc8201d1ba8 sp=0xc8201d1a00
nourish-server/apps.MountHQApp(0xc820234f00)
	/Users/mike/Code/nourish/server/src/nourish-server/apps/hq.go:26 +0x15a fp=0xc8201d1cb0 sp=0xc8201d1ba8
main.main()
	/Users/mike/Code/nourish/server/src/nourish-server/server.go:76 +0x559 fp=0xc8201d1f10 sp=0xc8201d1cb0
runtime.main()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc8201d1f60 sp=0xc8201d1f10
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201d1f68 sp=0xc8201d1f60
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
goroutine 5 [semacquire]:
sync.runtime_Syncsemacquire(0xc820130100)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8201300f0)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc8201300c0, 0xc82018c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820032138, 0xc82018c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/io/pipe.go:134 +0x50
bufio.(*Scanner).Scan(0xc82003ef20, 0x1000)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/scan.go:180 +0x877
github.com/Sirupsen/logrus.(*Logger).writerScanner(0xc820146e40, 0xc820032138)
	/Users/mike/Code/go/src/github.com/Sirupsen/logrus/writer.go:20 +0x129
created by github.com/Sirupsen/logrus.(*Logger).Writer
	/Users/mike/Code/go/src/github.com/Sirupsen/logrus/writer.go:12 +0x17b
goroutine 23 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82028a1e0)
	/usr/local/Cellar/go/1.5.1/libexec/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/Cellar/go/1.5.1/libexec/src/database/sql/sql.go:481 +0x336

```

Do you have any ideas or things to try to provide additional insight into the issue?
I've never used Delve before, so it's possible that this is an underlying Delve issue.

**Comment by lukehoban** [comment]
This looks like it's going to be a bug in Delve.

Can you try running `dlv debug` in the package directory?  Then enter `continue`.  If you see the same error you showed above, we can move this over to http://github.com/derekparker/delve.

**Comment by murz** [comment]
@lukehoban you're right it's a dlv issue. Thanks for the pointer

**Comment by dsp1589** [comment]
so what is the update for this issue? do you guys have any tracker no or something in github

**Comment by lukehoban** [comment]
Delve's issue tracker is here: https://github.com/derekparker/delve/issues.  I'm not sure if @murz opened a bug there on this specific issue yet.  If you are seeing any crashes like the above during debugging, and you can reproduce them using the command line `dlv` debugger, then you can report them to the Delve project.  

If in doubt though, feel free to report debugging problems here with repro steps.
