### ISSUE TITLE
Fail to debug, next, step in

### ISSUE THREAD

**Issue by nolanjian** [Microsoft/vscode-go#921]
When I update the latest vscode, I found that the debugger no longer work, fail to step in and next, and I don't know why, somewhat disappointed.

**errors:** 
2017/04/08 11:28:23 debugger.go:435: stepping
2017/04/08 11:28:25 debugger.go:412: continuing
2017/04/08 11:28:28 debugger.go:435: stepping
2017/04/08 11:28:32 debugger.go:435: stepping
Exception 0xc000001d 0x0 0x0 0x74a3c5
PC=0x74a3c5
github.com/gorilla/mux.NewRouter(0xcc00)
	C:/GoPath/src/github.com/gorilla/mux/mux.go:18 +0x45
main.initHandler(0x0)
	D:/src/intely_auth/server/server/main.go:73 +0x4a
main.main()
	D:/src/intely_auth/server/server/main.go:197 +0x148
goroutine 37 [IO wait]:
net.runtime_pollWait(0x3a9180, 0x72, 0x9bf430)
	C:/Go/src/runtime/netpoll.go:164 +0x60
net.(*pollDesc).wait(0xc04216c1a0, 0x72, 0x9bf430, 0x0)
	C:/Go/src/net/fd_poll_runtime.go:75 +0x3f
net.(*ioSrv).ExecIO(0xc042056100, 0xc04216c060, 0x815aeb, 0x7, 0x8404a8, 0xc0421620c6, 0x5, 0xa)
	C:/Go/src/net/fd_windows.go:196 +0xfe
net.(*netFD).Read(0xc04216c000, 0xc042266000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	C:/Go/src/net/fd_windows.go:452 +0x13d
net.(*conn).Read(0xc042056110, 0xc042266000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	C:/Go/src/net/net.go:181 +0x77
crypto/tls.(*block).readFromUntil(0xc0421563f0, 0x3a9240, 0xc042056110, 0x5, 0xc042056110, 0xc042173870)
	C:/Go/src/crypto/tls/conn.go:488 +0x9f
crypto/tls.(*Conn).readRecord(0xc042089500, 0x840c17, 0xc042089620, 0x4514b0)
	C:/Go/src/crypto/tls/conn.go:590 +0xcb
crypto/tls.(*Conn).Read(0xc042089500, 0xc042177000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/crypto/tls/conn.go:1134 +0x124
net/http.(*persistConn).Read(0xc042164000, 0xc042177000, 0x1000, 0x1000, 0x5, 0x44f400, 0xc042012120)
	C:/Go/src/net/http/transport.go:1316 +0x152
bufio.(*Reader).fill(0xc04203b260)
	C:/Go/src/bufio/bufio.go:97 +0x11e
bufio.(*Reader).Peek(0xc04203b260, 0x1, 0xc042173be5, 0x1, 0x0, 0xc04203b2c0, 0x0)
C:/Go/src/bufio/bufio.go:129 +0x6e
net/http.(*persistConn).readLoop(0xc042164000)
	C:/Go/src/net/http/transport.go:1474 +0x19d
created by net/http.(*Transport).dialConn
	C:/Go/src/net/http/transport.go:1117 +0xa3c
goroutine 38 [select]:
net/http.(*persistConn).writeLoop(0xc042164000)
	C:/Go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
	C:/Go/src/net/http/transport.go:1118 +0xa61
rax     0x7a6d00
rbx     0xc042091c80
rcx     0xc04201a000
rdi     0x5
rsi     0xc042091f88
rbp     0xc042091a30
rsp     0xc0420919f8
r8      0x5
r9      0x20
r10     0xc042015350
r11     0x246
r12     0x0
r13     0xffffffee
r14     0xa00
r15     0x6
rip     0x74a3c5
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
Failed to step.

**Comment by nolanjian** [comment]
relate to #809, get the newest dlv, problem solve
